### ISSUE TITLE
No DFU device found

### ISSUE THREAD

**Issue by johntyty912** [respeaker/usb_4_mic_array#20]
Hi,
I am using ubuuntu 16.04 with python2.7 and the Respeaker Mic Array v2.0. I have a ValueError  when I try to update the firmware.

Here is the error:

```
john@ubuntu:~/catkin_ws/src/respeaker_ros/usb_4_mic_array$ sudo python dfu.py --download 6_channels_firmware.bin
Traceback (most recent call last):
  File "dfu.py", line 229, in <module>
    main()
  File "/home/john/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/john/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/john/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/john/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "dfu.py", line 218, in main
    dev = XMOS_DFU()
  File "dfu.py", line 198, in __init__
    super(XMOS_DFU, self).__init__()
  File "dfu.py", line 73, in __init__
    raise ValueError('No DFU device found')
ValueError: No DFU device found
```
Please help me

**Comment by xiongyihui** [comment]
We can use commands like `lsusb` and `lsusb -d 2886: -v` to check the usb mic array. For example:

```
$ lsusb
Bus 003 Device 004: ID 2886:0018  
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
$ lsusb -d 2886: -v | grep DFU
      iInterface              8 SEEED DFU
        bcdDFUVersion                   1.10
```

The VID and PID of the device is `2886:0018`.

**Comment by ichbtm** [comment]
similar problem.
can't update firmware.

```
$ lsusb
Bus 001 Device 004: ID 2886:0018
Bus 001 Device 005: ID 0424:7800 Standard Microsystems Corp.
Bus 001 Device 003: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 002: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

```
 $ lsusb -d 2886: -v | grep DFU
Couldn't open device, some information will be missing
        bcdDFUVersion                   1.10
```

```
$ sudo python dfu.py --download 6_channels_firmware.bin
entering dfu mode
Traceback (most recent call last):
  File "dfu.py", line 229, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "dfu.py", line 220, in main
    with dev:
  File "dfu.py", line 104, in __enter__
    raise ValueError('No re-enumerated DFU device found')
ValueError: No re-enumerated DFU device found
```

**Comment by feature09** [comment]
On the windows10,I hava the same problem.

When I run the duf_window.py command, the device will disappear.

```D:\PycharmProjects\usb_4_mic_array-master>python get_index.py
Input Device id  0  -  Microsoft ÉùÒôÓ³ÉäÆ÷ - Input
Input Device id  1  -  ReSpeaker 4 Mic Array (UAC1.0)
Input Device id  2  -  Âó¿Ë·ç (Realtek High Definition


D:\PycharmProjects\usb_4_mic_array-master>python dfu_windows.py --download 6_channels_firmware.bin
entering dfu mode
Traceback (most recent call last):
  File "dfu_windows.py", line 235, in <module>
    main()
  File "C:\Python36\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python36\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Python36\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python36\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "dfu_windows.py", line 226, in main
    with dev:
  File "dfu_windows.py", line 108, in __enter__
    raise ValueError('No re-enumerated DFU device found')
ValueError: No re-enumerated DFU device found


D:\PycharmProjects\usb_4_mic_array-master>python get_index.py
Input Device id  0  -  Microsoft ÉùÒôÓ³ÉäÆ÷ - Input
Input Device id  1  -  Âó¿Ë·ç (Realtek High Definition
```

**Comment by yinbiao** [comment]
> Hi,
> I am using ubuuntu 16.04 with python2.7 and the Respeaker Mic Array v2.0. I have a ValueError when I try to update the firmware.
> 
> Here is the error:
> 
> ```
> john@ubuntu:~/catkin_ws/src/respeaker_ros/usb_4_mic_array$ sudo python dfu.py --download 6_channels_firmware.bin
> Traceback (most recent call last):
>   File "dfu.py", line 229, in <module>
>     main()
>   File "/home/john/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/john/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/john/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/john/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "dfu.py", line 218, in main
>     dev = XMOS_DFU()
>   File "dfu.py", line 198, in __init__
>     super(XMOS_DFU, self).__init__()
>   File "dfu.py", line 73, in __init__
>     raise ValueError('No DFU device found')
> ValueError: No DFU device found
> ```
> 
> Please help me

hi, Problem solved ？

**Comment by jst4apple** [comment]
Hi I have meet the same problem, and I have solved, if someone have same issue, may be you just didn,t plug your micphoe 
![image](https://user-images.githubusercontent.com/21069494/61800368-7a63d580-ae5f-11e9-88b5-00238b831c2f.png)

**Comment by johntyty912** [comment]
Turns out I just need to change the usb wire.

**Comment by turtec** [comment]
had the same issue .... changing the wire works. thanks @johntyty912

**Comment by yinbiao** [comment]
i have solved, It's about USB cable

**Comment by AlenYing** [comment]
@ichbtm I got the same problem like yours. Have you solved?

**Comment by srinivasbakki** [comment]
I had to change my drivers from WinUSB to libUSB-32

**Comment by aamorel** [comment]
> On the windows10,I hava the same problem.
> 
> When I run the duf_window.py command, the device will disappear.
> 
> ```
> D:\PycharmProjects\usb_4_mic_array-master>python get_index.py
> Input Device id  0  -  Microsoft ÉùÒôÓ³ÉäÆ÷ - Input
> Input Device id  1  -  ReSpeaker 4 Mic Array (UAC1.0)
> Input Device id  2  -  Âó¿Ë·ç (Realtek High Definition
> 
> 
> D:\PycharmProjects\usb_4_mic_array-master>python dfu_windows.py --download 6_channels_firmware.bin
> entering dfu mode
> Traceback (most recent call last):
>   File "dfu_windows.py", line 235, in <module>
>     main()
>   File "C:\Python36\lib\site-packages\click\core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Python36\lib\site-packages\click\core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "C:\Python36\lib\site-packages\click\core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Python36\lib\site-packages\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "dfu_windows.py", line 226, in main
>     with dev:
>   File "dfu_windows.py", line 108, in __enter__
>     raise ValueError('No re-enumerated DFU device found')
> ValueError: No re-enumerated DFU device found
> 
> 
> D:\PycharmProjects\usb_4_mic_array-master>python get_index.py
> Input Device id  0  -  Microsoft ÉùÒôÓ³ÉäÆ÷ - Input
> Input Device id  1  -  Âó¿Ë·ç (Realtek High Definition
> ```
> 
> When i use dfu.py command, not dfu_window.py, have the others problem.
> 
> ```
> D:\PycharmProjects\usb_4_mic_array-master>python dfu.py --download 6_channels_firmware.bin
> Traceback (most recent call last):
>   File "dfu.py", line 229, in <module>
>     main()
>   File "C:\Python36\lib\site-packages\click\core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Python36\lib\site-packages\click\core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "C:\Python36\lib\site-packages\click\core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Python36\lib\site-packages\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "dfu.py", line 218, in main
>     dev = XMOS_DFU()
>   File "dfu.py", line 198, in __init__
>     super(XMOS_DFU, self).__init__()
>   File "dfu.py", line 71, in __init__
>     devices = self.find()
>   File "dfu.py", line 61, in find
>     configuration = device.get_active_configuration()
>   File "C:\Python36\lib\site-packages\usb\core.py", line 875, in get_active_configuration
>     return self._ctx.get_active_configuration(self)
>   File "C:\Python36\lib\site-packages\usb\core.py", line 102, in wrapper
>     return f(self, *args, **kwargs)
>   File "C:\Python36\lib\site-packages\usb\core.py", line 239, in get_active_configuration
>     bConfigurationValue=self.backend.get_configuration(self.handle)
>   File "C:\Python36\lib\site-packages\usb\backend\libusb0.py", line 510, in get_configuration
>     100)
>   File "C:\Python36\lib\site-packages\usb\backend\libusb0.py", line 593, in ctrl_transfer
>     timeout
>   File "C:\Python36\lib\site-packages\usb\backend\libusb0.py", line 431, in _check
>     raise USBError(errmsg, ret)
> usb.core.USBError: [Errno None] b'libusb0-dll:err [control_msg] sending control message failed, win error: '连到系统上的设备没有发挥作用。'
> ```

Hi, do you remember how you solved the problem ? i have the exact same one

**Comment by vivian0239** [comment]
Thank you! I have a same cable issue. I  waste a lot of time until read this.

**Comment by steveseguin** [comment]
Couldn't get it to work on my Windows 10 pc; plugged it into a Mac though (same cable) and it worked like a charm.  Oh well.

**Comment by Robopiyf** [comment]
> Turns out I just need to change the usb wire.

Which port is the corrected one?

**Comment by LeeHieu134** [comment]
I had the same problem; have you solved it yet?
