### ISSUE TITLE
Random Crash of Respeaker Mic array V2.

### ISSUE THREAD

**Issue by sradmard** [respeaker/usb_4_mic_array#37]
Hi,
I have a Respeaker Mic array V2.0 and I have updated my firmware through this package using the "6_channels_firmware.bin" file. I use the device under Ubuntu 16.04 and use the [respeaker_ros](https://github.com/furushchev/respeaker_ros) package to get the DOA and the audio input. 
However, I get the following error randomly sometimes, which causes the respeaker to crash, where I have to restart my software entirely. I am not sure where the problem originates from, and would appreciate any feedback on this matter. 

`[roslaunch][ERROR] 2020-01-29 12:04:51,077: remote[192.168.0.6-0]: M cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 429496729
[roslaunch][ERROR] 2020-01-29 12:05:18,038: remote[192.168.0.6-0]: 5, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/timer.py", line 235, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/home/jdqadmin/catkin_ws/src/jdq_3sr_aether_robot/jdq_3sr_aether_voice/script/respeaker_porcupine.py", line 269, in doa_on_timer
    is_voice = self.respeaker.is_voice()
  File "/home/jdqadmin/catkin_ws/src/jdq_3sr_aether_robot/third_party/respeaker_ros/scripts/respeaker_node.py", line 199, in is_voice
    return self.read('VOICEACTIVITY')
  File "/home/jdqadmin/catkin_ws/src/jdq_3sr_aether_robot/third_party/respeaker_ros/scripts/respeaker_node.py", line 172, in read
    0, cmd, id, length, self.TIMEOUT)
  File "/home/jdqadmin/.local/lib/python2.7/site-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/home/jdqadmin/.local/lib/
[roslaunch][ERROR] 2020-01-29 12:05:24,256: remote[192.168.0.6-0]: python2.7/site-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/home/jdqadmin/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
USBError: [Errno 19] No such device (it may have been disconnected)`

**Comment by KillingJacky** [comment]
Hi @sradmard, we haven't received similar reports about USB detaching under Ubuntu 16.04, if you haven't hacked the USB driver stuff of your system,  I would assume that this is hardware contacting issue. Also, if next time it crashes, please dump the kernel log

```shell
# dmesg
# tail -n 1000 /var/log/kern.log 
```
