### ISSUE TITLE
Tuning.py (AttributeError: 'array.array' object has no attribute 'tostring')

### ISSUE THREAD

**Issue by Retroman445** [respeaker/usb_4_mic_array#49]
Running tuning.py gives me this error.

```
Traceback (most recent call last):
  File "/home/jeroen/Scripts/respeaker/usb_4_mic_array/tuning.py.1", line 197, in <module>
    main()
  File "/home/jeroen/Scripts/respeaker/usb_4_mic_array/tuning.py.1", line 181, in main
    print('{:24} {}'.format(name, dev.read(name)))
  File "/home/jeroen/Scripts/respeaker/usb_4_mic_array/tuning.py.1", line 109, in read
    response = struct.unpack(b'ii', response.tostring())
AttributeError: 'array.array' object has no attribute 'tostring'
```

Solved it my changing this line

`        response = struct.unpack(b'ii', response.tostring())`

to this

`        response = struct.unpack(b'ii', response)`

**Comment by DavidGoedicke** [comment]
Just made a pull request to address this issue.

See #54 .

**Comment by goldyfruit** [comment]
I got the same issue, and @DavidGoedicke's PR worked for me.
