### ISSUE TITLE
ValueError: No re-enumerated DFU device found

### ISSUE THREAD

**Issue by Robopiyf** [respeaker/usb_4_mic_array#64]
entering dfu mode
Traceback (most recent call last):
  File "dfu_windows.py", line 235, in <module>
    main()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "dfu_windows.py", line 226, in main
    with dev:
  File "dfu_windows.py", line 108, in __enter__
    raise ValueError('No re-enumerated DFU device found')
ValueError: No re-enumerated DFU device found

**Comment by Gavin-00** [comment]
I also encounter this problem
